#swagger api info
swagger:
  api-info:
    version: 1.0
    title: Formicary REST
    description: API for crowdfunding platform
    license: Open Source
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0
    contact:
      name: Alexandr Heilash
      url: https://www.linkedin.com/in/alexandr-heilash-6b0055173/
      email: alexandr.heilash@gmail.com

spring:
  profiles:
    active: '@activated.profile@'
  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB
  kafka:
    listener:

      missing-topics-fatal: false

#hibernate search
hibernate:
  search:
    default:
      directory_provider: filesystem
      indexBase: /data/index/campains

management:
  server:
    servlet:
      context-path: /management
    port: 8110
  endpoint:
    metrics:
      enabled: false
  endpoints:
    web:
      base-path: /

cloud:
  aws:
    region:
      static:
    stack:
      auto: false
    credentials:
      accessKey:
      secretKey:
    s3:
      imagesBucket:
      region:

#SOCIAL
  social:
    facebook:
      appId:
      appSecret:
    twitter:
      apiKey:
      apiSecretKey:
      accessToken:
      accessTokenSecret:
    google:
      appSecret:
      appId:
