#swagger api info
swagger:
  api-info:
    version: 1.0
    title: Formicary REST
    description: API for crowdfunding platform
    license: Open Source
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0
    contact:
      name: Alexandr Heilash
      url: https://www.linkedin.com/in/alexandr-heilash-6b0055173/
      email: alexandr.heilash@gmail.com

spring:
  profiles:
    active: '@activated.profile@'

#AWS S3
cloud:
  aws:
    credentials:
      accessKey: AKIAIYFMKY3K7ONV5Y5A
      secretKey: 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
    region.static: us-east-2
    stack.auto: false
    s3:
      tripImagesBucket: heilash
      objectUrlPrefix: https://d3ocamvut00iju.cloudfront.net/
      region: us-east-2


#  social:
#    facebook:
#      appId: 526762058188362
#      appSecret: b01c60f2ef80147051454f4ceadcf1b6
#    twitter:
#      apiKey: uM2mWowm8xq8o6gp6buywbb51
#      apiSecretKey: GSgplBaE8JJ3N0WkbZHZwRnNvvibTrWJw89AqzeFqBC3BvTgfp
#      accessToken: 1219651235722203136-epn3m5DOQkTj3Ksna6po71medWwPN0
#      accessTokenSecret: 5JQw4p4OgkTXdZTtvXYqDBc3vv1CvE2fkfWSij3pXJMp3
